# Generated by Django 6.0 on 2025-12-13 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
