# Generated by Django 6.0 on 2025-12-13 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_analyzer', '0002_analysis_error_message_alter_analysis_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysis',
            options={'ordering': ['-created_at'], 'verbose_name': 'Analysis', 'verbose_name_plural': 'Analyses'},
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='image',
        ),
    ]
