# Generated by Django 6.0 on 2025-12-14 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_analyzer', '0003_alter_analysis_options_remove_analysis_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='product_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='product_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='barcode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
